/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registersystem;

import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Restrictions;
import sessions.SessionCreate;

/**
 *
 * @author Akshai
 */
public class systemregister extends javax.swing.JFrame {

    InetAddress addr;
    Map<String, String> env;
    int locid;

    public systemregister() {
        try {
            ThemeMetal tm = new ThemeMetal();
            initComponents();
            SessionCreate sc = new SessionCreate();
            setlocations();
            addr = InetAddress.getLocalHost();
            env = System.getenv();
            sysname.setText("" + java.net.InetAddress.getLocalHost().getHostName());
            ipadd.setText("" + addr.getHostAddress());
            username.setText("" + System.getProperty("user.name"));
            os.setText("" + System.getProperty("os.name"));
        } catch (UnknownHostException ex) {
            Logger.getLogger(systemregister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ipadd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        locincharge = new javax.swing.JTextField();
        os = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sysname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enabled = new javax.swing.JCheckBox();
        cc = new javax.swing.JCheckBox();
        loc = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        servicecenter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("IP Address");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("System In Charge");

        ipadd.setEditable(false);
        ipadd.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Location");

        locincharge.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        os.setEditable(false);
        os.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel1.setText("Configure System");

        sysname.setEditable(false);
        sysname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Operating System");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("System Name");

        enabled.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        enabled.setSelected(true);
        enabled.setText("Enabled");

        cc.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cc.setText("Is Cash Counter");

        loc.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Service Centers");

        servicecenter.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        servicecenter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                servicecenterKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setText("Register System");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("User Account Name");

        username.setEditable(false);
        username.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(servicecenter, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                                    .addComponent(locincharge, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(os)
                                        .addGap(18, 18, 18)
                                        .addComponent(cc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(enabled))
                                    .addComponent(loc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sysname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(username)
                                    .addComponent(ipadd))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sysname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicecenter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locincharge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(os, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enabled)
                    .addComponent(cc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void servicecenterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_servicecenterKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ModuleSelect abc = new ModuleSelect();
            abc.setModal(true);
            abc.setVisible(true);
            servicecenter.setText("" + ModuleSelect.selectedname);
        }
    }//GEN-LAST:event_servicecenterKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveAction();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new systemregister().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cc;
    private javax.swing.JCheckBox enabled;
    private javax.swing.JTextField ipadd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox loc;
    private javax.swing.JTextField locincharge;
    private javax.swing.JTextField os;
    private javax.swing.JTextField servicecenter;
    private javax.swing.JTextField sysname;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void setlocations() {
        System.out.println("ahaaa");
        sessions.SessionCreate.session = sessions.SessionCreate.factory.openSession();
        try {
            sessions.SessionCreate.session.beginTransaction();
            Criteria cr = sessions.SessionCreate.session.createCriteria(APPLOCATIONS_POJO.class);
            cr.add(Restrictions.eq("ENABLED", 'Y'));
            cr.add(Restrictions.eq("DELETED", 'N'));
            List results = cr.list();
            System.out.println("res" + results.size());
            loc.removeAllItems();
            loc.addItem("Select");
            loc.setSelectedItem("Select");
            for (Iterator iterator = results.iterator(); iterator.hasNext();) {
                APPLOCATIONS_POJO lsp = (APPLOCATIONS_POJO) iterator.next();
                loc.addItem(lsp.getLocation_name());
            }
            sessions.SessionCreate.session.getTransaction().commit();
        } catch (HibernateException e) {
            if (sessions.SessionCreate.session.getTransaction() != null) {
                sessions.SessionCreate.session.getTransaction().rollback();
                System.out.println("hmmmm....");
            }
            JOptionPane.showMessageDialog(null, "Error:-" + e, "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(e.getMessage());
        } finally {
            sessions.SessionCreate.session.close();
        }
    }

    public void saveAction() {
        sessions.SessionCreate.adminses = sessions.SessionCreate.factory.openSession();
        try {
            sessions.SessionCreate.adminses.beginTransaction();
            APP_REGISTEREDSYSTEMSpojos lb = new APP_REGISTEREDSYSTEMSpojos();
            lb.setSYSNAME(sysname.getText());
            lb.setIP(ipadd.getText());
            getlocations((String) loc.getSelectedItem());
            lb.setLOCATIONID(locid);
            if (cc.isSelected()) {
                lb.setISCASHCOUNTER('Y');
            } else {
                lb.setISCASHCOUNTER('N');
            }
            lb.setOS(os.getText());
            lb.setOWNERID(0);////to be changed
            lb.setDELETED('N');
            if (enabled.isSelected()) {
                lb.setENABLED('Y');
            } else {
                lb.setENABLED('N');
            }
            lb.setSERVICECENTERS(ModuleSelect.selectedid);
            lb.setUSERACCOUNTNAME(username.getText());
            sessions.SessionCreate.adminses.save(lb);
            sessions.SessionCreate.adminses.flush();
            sessions.SessionCreate.adminses.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Your changes has been saved...", "saved", JOptionPane.INFORMATION_MESSAGE);
        } catch (HibernateException e) {
            if (sessions.SessionCreate.adminses.getTransaction() != null) {
                sessions.SessionCreate.adminses.getTransaction().rollback();
                System.out.println("hmmmm....");
            }
            JOptionPane.showMessageDialog(null, "Could not save. Some error occured." + e, "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(e.getMessage());
            e.printStackTrace();
        } finally {
            sessions.SessionCreate.adminses.close();
        }
    }

    private void getlocations(String location) {
        System.out.println("ahaaa");
        sessions.SessionCreate.session = sessions.SessionCreate.factory.openSession();
        try {
            sessions.SessionCreate.session.beginTransaction();
            Criteria cr = sessions.SessionCreate.session.createCriteria(APPLOCATIONS_POJO.class);
            cr.add(Restrictions.eq("ENABLED", 'Y'));
            cr.add(Restrictions.eq("DELETED", 'N'));
            cr.add(Restrictions.eq("Location_name", location));
            List results = cr.list();
            for (Iterator iterator = results.iterator(); iterator.hasNext();) {
                APPLOCATIONS_POJO lsp = (APPLOCATIONS_POJO) iterator.next();
                locid = lsp.getLocation_id();
            }
            sessions.SessionCreate.session.getTransaction().commit();
        } catch (HibernateException e) {
            if (sessions.SessionCreate.session.getTransaction() != null) {
                sessions.SessionCreate.session.getTransaction().rollback();
                System.out.println("hmmmm....");
            }
            JOptionPane.showMessageDialog(null, "Error:-" + e, "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(e.getMessage());
        } finally {
            sessions.SessionCreate.session.close();
        }
    }
}
